### PR TITLE
Encoding and Python 3

### PR DESCRIPTION
**Pull request by vincent-lg**
#### Brief summary of issue

The current branch running on Python 3.5 of Python has some issues with encoding that most ASCII users wouldn't notice.  Basically, it's either ASCII, or utf-8, the rest doesn't work.  And while I would be happy to have everyone using utf-8, it's clearly not a good choice, particularly with Evennia's settings.

#### Steps to reproduce the issue / Reasons for adding feature:

To see the problem:

1. Install a fresh Evennia with the develop-py3 branch.
2. In the `server/conf/connection_screens.py` file, append some utf-8 in the file (see mine below).
3. With a client that uses a different encoding (mine uses latin-1 for instance), connect to localhost:4000.  You will see an error on the accented character, as you should (default encoding isn't changed).
4. Use the `@encoding` command to change your output encoding.  In my case: `@encoding latin-1` .
5. And type `look` to see... the exact same error.

```python
# connection_screen
CONNECTION_SCREEN = """
médor
|b==============================================================|n
 Welcome to |g{}|n, version {}!

 If you have an existing account, connect to it by typing:
      |wconnect <username> <password>|n
 If you need to create an account, type (without the <>'s):
      |wcreate <username> <password>|n

 If you have spaces in your username, enclose it in quotes.
 Enter |whelp|n for more info. |wlook|n will re-show this screen.
|b==============================================================|n""" \
    .format(settings.SERVERNAME, utils.get_evennia_version())
```

(Yes, it's the é in "médor", which is a beautiful dog name).

#### Error output / Expected result of feature

What happens?  I would like to know.  It's not just an error of the `@encoding` command, it's the encoding system that's a bit broken.  Full debugging didn't allow me to find the proper solution... but I identified some possible root causes and here's my thinking:

1. `to_str` is called A LOT.  This is probably a very bad idea for encoding support.  In Python 3, every string within the program should be utf-8 (str type).  Converting to other encoding (bytes) should only happen before every evennia-related processing (input), and just before submitting to the client (output).  Some functions (like `pickle.dumps` which is used by `amp.dumps`) return bytes.  Is that where the encoding should be handled?  Turning this bytes into a string afterward (look at the `server.portal.amp.dumps` function) might break some things.
2. The only point where I found the ENCODING protocol flag being used is in `server/sessionhandler.py`.  It converts bytes to string following the encoding.  Again, I would think the other way around would be preferable: converting string to bytes before sending them... but I don't know enough of Evennia's structure to be sure.  And since there's the AMP to consider between them, I don't feel like coming up with a solution by myself, without guidance.

In my opinion, the greatest problem is the excessive `to_str` calls, but again, that might not be the reason for the problem.  If anyone wants additional debugging and can orient me in the right direction, I'll take it.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:

* Evennia branch: develop-py3

### CODE REVIEW

**Comment by vincent-lg** [comment]
So I've tried to fix the issue.  The following workflow has been adopted:

1. I've maintained the input bytes-to-str conversion as it was, since it seemed to be working correctly.  Notice that more unity might be preferable but as it is, the fix works and doesn't disturb the code too much.
2. I removed the `to_str` in `amp.dumps` and `amp.loads`.  I didn't notice any problem with that and it seemed to fix quite a lot of bugs but I don't know how wise it was.
3. I added a method in the session, called `try_encode`.  Its job is simple: to try to encode a `str` into `bytes`.  If it can, it uses the protocol flag.  This method is to be called right before writing to the protocol.  In other words, it is only used for output (and only at the very last moment).

> Notice that the calls to `try_encode` are done in `telnet.py` directly, which might not be the best option.  The webclient keeps on working and handling accents correctly, but other protocols might have to be updated.  Before doing that, though, I would like to know if what I'm doing is wise and advisable.  I tried to maintain code compatibility and improve encoding/decoding logic within Python 3's new workflow.

Overall, the fix works: the provided example works as expected (that is, the bytes for é are different for utf-8 and latin-1 as they should be).

**Comment by Griatch** [comment]
That `try_encode` appears to just be patching the symptom rather than fixing the issue. I'll look some more at it, but it seems wrong to edit this at the telnet level. If things are wrong there, they will be wrong before that level too, meaning this will, as you say, not help for other protocols.

**Comment by vincent-lg** [comment]
It's not just a "patch" to deal with the encoding.  It actually moves the encoding process.  The problem is that telnet (and other protocols) call `self.protocol.write`, which is (I think) the very last stage, and `protocol.write` waits for bytes.  So I do the converting from str to bytes just before calling it.  I don't really know how that could be better fixed, perhaps a generic method to call instead of writing to the protocol, which method would both convert to bytes and then send over the wire.  Open debate.

As for the workflow, everything remains a str (including over AMP) until the moment when we write to the actual protocol.  The `amp.dumps` returns bytes, to be sure, but it's a pickled version (pickle now returns bytes, not str).  There's no encoding taking place before sending to the AMP.  So the AMP is responsible for the output encoding at least.

**Comment by vincent-lg** [comment]
I made a few changes to clarify.  The `try_encode` had a somewhat unhelpful (and a bit untrustworthy) name.  I changed it to `encode_output` and clarified the documentation a little.  The good news is, as far as I can see, no other protocol needs to be changed, though I only checked the protocols in `server/portal`.  The `encode_output` can still work with `str` and `butes` (in the latter case, the output is returned as-is) however.  But I still believe this is much cleaner this way, as it happens just before sending the message to the protocol, or at the very least, just before protocol-specific actions that should work on bytes anyway.  My opinion :D .

**Pull request merged**
