### PR TITLE
Fix merge order with spawn() and prototype_parents

### PR DESCRIPTION
**Pull request by jerryaldrichiii**
#### Brief overview of PR changes/additions

Fixes merge order when using spawn() with prototype_parents (see tests for an example)

#### Motivation for adding to Evennia

I <3 you all and want to help :D

#### Other info (issues closed, discussion etc)

Fixes issues described in #2474

### CODE REVIEW

**Comment by Griatch** [comment]
@jerryaldrichiii 
Thanks for the fix! While I agree there is a bug somewhere, I'm not sure why this would fix the issue at hand though - except for the special case where the prototype-parent uses the "simple" type of Attribute definition (`{attrname: value}`) while the child uses full Attribute definitions (`{'attrs': [(key, value, category, locks), ...]}`). It would seem it would fail in the opposite direction if the Attribute types were reversed between parent and child. 

Am I missing something here?

**Comment by jerryaldrichiii** [comment]
To be honest, I'm not exactly sure why this fixes things either.

My guess is maybe something somewhere else iterates over this list and order matters for merging? I couldn't find such a thing and the prototype inheritance code confuses me greatly :(

I didn't test a simple + full attributes combination, but the example test uses simple attributes only so I'm not sure if that plays a role or not.

**Comment by Griatch** [comment]
@jerryaldrichiii I fixed this in a different way. The issue is how the custom protparent was added - basically the base prototype was converted to the full attribute form (`{"attrs": [(key, value, category, locks), ...]`) while the protototype-parent remained using the simple-form (`{key:value}`). So when it came to do the update, the prototype had `{"attrs": ("magic", "True", None, ")}` while the parent had `{"magic": False}`. When the prototype-dicts merged, both thus had different keys and both ended up in the dict. Your change made the full one take precedence (True) instead of the simple one (False). The real issue is that there are two representations of the magic value in the prototype; once homogenizing the parent to the same form, the bug is resolved. 
If you are interested, you can see the fix here: https://github.com/evennia/evennia/commit/0129786c3d5f1b92fef480849beb9a95d2494455 

Thanks for the help finding a clue to the solution! Closing this now.

**Comment by jerryaldrichiii** [comment]
Wonderful. Thanks for taking the time to track down the real issue! Also, thanks for the explanation as well! It's very clear.

Every time I interact with this project or its people I learn a ton. You folks are most awesome.

**Pull request closed without merging**
