### PR TITLE
Refactor CI for postgres

### PR DESCRIPTION
**Pull request by ChrisLR**
#### Brief overview of PR changes/additions
PSQL tests usually fail after 30 minutes, looking at the actions file I saw the pg version is very outdated.

#### Motivation for adding to Evennia
Fixing the CI

### CODE REVIEW

**Comment by ChrisLR** [comment]
@Griatch the only change worth keeping so far is using postgres by declaring it in services instead of using another action, it should let us provide a conf to postgres more easily, I did research a few ways to make the tests faster, using one or a few parameters mentioned here

https://www.postgresql.org/docs/current/non-durability.html

However I don't understand why the pg tests would be that slow compared to other databases so I would have to investigate more.

**Comment by ChrisLR** [comment]
Its on the TODO pile, I'll come back to it :sweat_smile:

**Comment by Griatch** [comment]
Ping. :)

**Comment by Griatch** [comment]
@ChrisLR Another ping

**Comment by ChrisLR** [comment]
@Griatch Still experimenting, unsure why having the two pg tests run in parallel makes one of them fail while one after the other works

**Comment by Griatch** [comment]
@ChrisLR Added Python3.12 to the CI matrix, and the postgres issue remains :disappointed:

**Comment by ChrisLR** [comment]
@Griatch using the code from this PR ? :(

**Comment by Griatch** [comment]
Nono, just adding a data point since you were looking at this.

**Comment by ChrisLR** [comment]
@Griatch :relieved: great, so there's a chance this PR is sufficient, I will add 3.12 to it and see

**Comment by Griatch** [comment]
@ChrisLR This is still marked as a Draft. Is this still being worked on?

**Comment by ChrisLR** [comment]
@Griatch sorry about the delay, yes this is still on my plate.

**Comment by ChrisLR** [comment]
No longer worked after resolving conflicts.
It likely didn't solve the root issue.
Closing for now.

**Pull request closed without merging**
