### PR TITLE
Pending merge: ANSIString+mxp issue

### PR DESCRIPTION
**Pull request by Griatch**
@Kelketek 

As discussed I made a separate branch with a unittest for the ANSIString + mxp issue. This goes towards resolving the main point of #625.

### CODE REVIEW

**Comment by Kelketek** [comment]
@Griatch Rebased this against master and tweaked the test code layout a little as well. Please look at this and let me know if you see any issues with the proposed solution.

**Comment by Kelketek** [comment]
Per discussion in IRC, having ANSIString be MXP aware is not the correct approach.

**Comment by Griatch** [comment]
Not sure closing this was the conclusion of the IRC chat. I though the conclusion was that the length of ANSIString should be MXP aware although it should not explicitly map the ansi tag internally?

With this closed we are otherwise nowhere nearer to resolving #625.

**Comment by Kelketek** [comment]
@Griatch ANSIString's length should not be MXP aware. Instead, a function should be placed in `utils` named m_len() that checks if an object is of class base_string, and if it is, uses a regex substitution to determine the length of the string without MXP, and if it isn't, just uses len(). This is because if we made ANSIString's len aware of MXP, it would make its length reporting inconsistent with its indexes, and this could have odd consequences.

**Pull request closed without merging**
