### PR TITLE
bugfix: change pathing to relative url

### PR DESCRIPTION
**Pull request by iLPdev**
#### Brief overview of PR changes/additions
changes url pathing for slot validation test

#### Motivation for adding to Evennia
if following tutorial, runtime errors for conflicting models without fix

### CODE REVIEW

**Review by Griatch — CHANGES_REQUESTED** [review]
This breaks Evennia's test suite. Not sure if you can use a relative path in a mock patch.

**Comment by InspectorCaracal** [comment]
I think this maybe was supposed to be a documentation fix? It looks as though the path here is the one the function would have while going through the tutorial in your own game.

**Comment by Griatch** [comment]
If it could be patched relatively that would be a benefit, because I suppose this becomes an issue if you copy&paste verbatim.

**Comment by iLPdev** [comment]
yeah, this is supposed to be about the documentation in the tutorial example.

**Comment by Griatch** [comment]
This PR can't merge though; because while the tutorial assumes that you are working in your own game dir, the Evennia-side code must operate from inside the Evennia repository, and this PR breaks that. Closing.

**Pull request closed without merging**
