### PR TITLE
fixing memory leaks

### PR DESCRIPTION
**Pull request by a-rodian-jedi**
**Brief overview of PR changes/additions**

- Fixes a memory leak in Portal Telnet connections
- Forces weak references on Telnet negotiation objects
- Stops _nop_keepalive LoopingCall on disconnected sessions

**Motivation for adding to Evennia**
Community complaints about memory leaks

**Other info (issues closed, discussion etc)**
https://github.com/evennia/evennia/issues/3225

This is not everything. There is also a leak in AttributeHandler, I believe, but I will separate that. I think these fixes should come 1 at a time for stability.

### CODE REVIEW

**Review by Griatch — CHANGES_REQUESTED** [review]
Thanks for picking this up again (sorry to see the memory analysis tools go, but good to see these leaks fixed). 
This currently fails unit tests though; looks like there is an issue with weakref being used in a place where a dict is expected.

**Comment by a-rodian-jedi** [comment]
Aha, the unit tests need () on the protocol as well. Very easy to address, I can get to it shortly.

**Comment by a-rodian-jedi** [comment]
From my local testing, the unit tests should now be operational. Even though I checked many times and used edit searching and everything... I still managed to miss a couple of `self.protocol` lines that needed `()`. I think I have them all now.

**Review by Griatch — APPROVED** [review]
Thanks for finishing this up. Will be interesting to see if there are any other side effects of this down the line. And looking forward to the one for the AttributeHandler :wink:

**Pull request merged**
