### PR TITLE
2620 fix prototype loading

### PR DESCRIPTION
**Pull request by ChrisLR**
#### Brief overview of PR changes/additions
This ensures the prototypes are loaded before being searched

#### Motivation for adding to Evennia
Fix issue

#### Other info (issues closed, discussion etc)
https://github.com/evennia/evennia/issues/2620

### CODE REVIEW

**Review by Griatch — CHANGES_REQUESTED** [review]
Thanks for the PR! Curiously, there seems to be some failing unit tests though ... while there are some issues with the mysql/postgres builds in develop, the sqlite3 test should pass (see the previous https://github.com/evennia/evennia/runs/4833101042?check_suite_focus=true). There seems to be some failing object lookups from this PR. Unclear why that would arise from this change but it seems to be new.

**Comment by Griatch** [comment]
That looks better. The reason the sqlite build fails now is due to a bug in the CI script that I fixed (it fails since you of course don't have the evennia docker creds).

**Comment by ChrisLR** [comment]
@Griatch there's still a remaining issue hidden somewhere, some of the tests override settings and let the teardown clean it but somehow it doesn't. The temporary work around was to enforce the DEFAULT_HOME back but the override_settings and the teardown are supposed to rollback the changes...

**Comment by Griatch** [comment]
@ChrisLR That's fine, it's already a step forward and the test suite works when I built it locally. If you want to dig further into the testing logic, best to do so in a separate PR :) I merged this now.

**Pull request merged**
