### PR TITLE
Update menu_login to use EvMenu.

### PR DESCRIPTION
**Pull request by ahmedcharles**
This relies on the EvMenu updates, so those should be merged first.

### CODE REVIEW

**Comment by Griatch** [comment]
This version of menu_login seems to have severely diminished functionality compared to the old non-EvMenu version, and as such I can't accept it in this form. 

The old menu_login did validation at every step and asked to to correct your input before continuing. It also allowed you to return back to the root menu to start over if you changed your mind by giving an empty input (which will never be a valid playername/password anyway).

This one will allow any input, including empty space and then checks the total input only at the end - which leads to abruptly dropping connection completely if any of the previous outputs were wrong - this is very frustrating to the end user and now how menu login systems work normally.

**Comment by ahmedcharles** [comment]
My main goal here was simplifying the flow of the code.

I'll make some changes and test them and submit an updated PR.

**Comment by ahmedcharles** [comment]
I'm refactoring the rest of the login code so this will hopefully get easier.

**Comment by Griatch** [comment]
Any progress on this refactoring?

**Comment by ahmedcharles** [comment]
I've been busy, but I'll take a look this weekend, hopefully.

**Comment by Griatch** [comment]
This still seems like a very useful update, hope it's still in the works.

**Comment by Griatch** [comment]
This was instead implemented from scratch by vlegoff in  #961, so closing this.

**Pull request closed without merging**
