### PR TITLE
Removed single quote parsing from player 'connect' and 'create' comma…

### LINKED ISSUE #1076: Creating a player from pre-login containing apostrophe
#### Brief summary of issue / Description of requested feature:
Creating a character from pre-login containing apostrophe yields unexpected and varied results, requires manual intervention.

#### Steps to reproduce the issue / Reasons for adding feature:

1. `create T'Pring Vulcan` 
2. `create "T'Pau" Vulcan`
3. `create Muad’Dib Dune`

#### Error output / Expected result of feature

The first creates a player and character named `T`

The second yields:
`Usage (without <>): create <name> <password>`
`If <name> or <password> contains spaces, enclose it in quotes.`

The third yields:
`Playername can max be 30 characters or fewer. Letters, spaces, digits and @/./+/-/_ only.`

The user who attempts this receives conflicting information and no success, requiring a manual renaming to name the character object what the user wants.

#### Extra information, such as Evennia revision/repo/branch, operating system and ideas for how to solve / implement:
Latest revision, Evennia, master branch

Escape input to allow a larger variety of character names, instruct that creating a character with a name containing an apostrophe requires special action - renaming in web admin after creation.

### PR DESCRIPTION
**Pull request by robbintt**
#### Brief overview of PR changes/additions

Removes option to surround player name or password with single quotes in the regular expression raw string.

#### Other info (issues closed, discussion etc)

Fixes #1076

### CODE REVIEW

**Comment by Griatch** [comment]
This looks good, I'll test it and likely merge it when I get back to my dev machine. Thanks!

One thing I wonder is if one should add a counter to check for unclosed double quotes at some point (not necessarily for this PR, just an idle thought when reading this).

**Comment by robbintt** [comment]
I don't think unbalanced matters with split, especially with stripping:
```
>>> import re
>>> re.split(r"\"", "\"hello\"world\"how\"areyou\"")
['', 'hello', 'world', 'how', 'areyou', '']
>>> [x.strip() for x in re.split(r"\"", "\"hello\"           \"how\"you\"")]
['', 'hello', '', 'how', 'you', '']
```
As long as you have the split between names, all whitespace turns into a single space on join.

**Comment by Griatch** [comment]
@robbintt 

Well, it would matter if the last part of the enclosed (or non-enclosed) string is meant to be the password ...

**Comment by robbintt** [comment]
@Griatch I woke up this morning and realized I could just add single quote support very easily with these changes in place.  In the future it may be helpful to factor out the regex glyph whitelister.

**Comment by Griatch** [comment]
This was merged with a rebase.

**Pull request closed without merging**
