### PR TITLE
Implements user input auditing.

### PR DESCRIPTION
**Pull request by strikaco**
#### Brief overview of PR changes/additions
Implements auditing of all strings submitted to the ServerSessionHandler by connected players to monitor user behavior. Where possible, the session IP address, player object#dbref, character object#dbref, and room occupied#dbref are resolved and included inline.

Tested in MULTISESSION_MODE = 3 to address even the wackiest of deployments.

Disabled by default; can be enabled in settings.

The log format is admittedly rough; currently working on standardization for easier parsing.

#### Motivation for adding to Evennia
No auditing functionality currently exists.

#### Other info (issues closed, discussion etc)
Attempts to provide a historical record by which to address the concerns raised in #1375 (being able to "check other player objects and see if that user was linked to any other player objects and if so, find out what they were up to on the MU") while declining to adopt the proposed implementation.

This does NOT attempt to address the concerns raised in #1383, as it does not provide any insight into network activity.

### CODE REVIEW

**Comment by DamnedScholar** [comment]
Sorry to take some of the thunder from this PR, but what if this were implemented differently? The same goal could be achieved by having each command call a global hook function and pass its own object to that function. If the command's `__dict__` includes `"audit": "false"`, for example, then the command would be excluded from the log. The implementation of a global "on command invocation" hook function would allow for a wide variety of other features to be built on the same foundation, such as having some commands interrupt others (I know @Treatz - streetwitch - is trying to implement a command that can be directly interrupted by other commands).

**Comment by BlauFeuer** [comment]
In #1375, I proposed this could be done in game code in `commands/command.py` using the `at_pre_cmd` hook.

At this point, the session, "player" account, and puppeted object is known, along with the command string entered.  It can be pushed into a log and/or displayed in the console, and can be expanded as needed without having to build auditing into the server even if it's not used by default.

As for the use case of a command interrupted by another command, that would work similarly as a game-specific change where the command used is written on the puppeted object to allow for others to trigger it to be interrupted.

**Comment by Griatch** [comment]
@DamnedScholar: Command interruption is already possible (see several tutorials dealing with this), I don't think we need another hook only for this. 

@BlauFeuer: Ah, right, using the `at_pre_cmd` of a command parent would make for a very easily over-ridable hook location too, with the additional advantage of being able to use classes to further customize eventual audit for different command groups. Hm. For Commands, using `at_pre_cmd` gives more flexibility. strikaco's centralized logger offers the potential ability able to catch *all* outgoing data though (OOB, script echoes etc), for those that would want that.

**Comment by DamnedScholar** [comment]
@Griatch Which tutorials? Searching the wiki for the word "interrupt" isn't turning up anything.

**Comment by BlauFeuer** [comment]
All outgoing data auditing, yes I agree that would be useful for debugging in addition to security.   I don't disagree with this PR and I applaud  strikaco's efforts.  Currently I log all no match commands for debugging and determining which command aliases would be most beneficial, along with specific admin commands similar to the 'audit': False flag idea. My main point is that expanding the framework to allow game code to fill in the gaps for specific needs is the key to making Evennia extensible and broadening its user base.

**Comment by Griatch** [comment]
@DamnedScholar https://github.com/evennia/evennia/wiki/Command-Duration#abortable-commands. Also https://github.com/evennia/evennia/wiki/Command-Duration could be useful.

**Comment by strikaco** [comment]
@Griatch 
> I think however that something like this must probably be implemented as something the user can override. The easiest way would be to call a hook in data_in. What that hook calls is defined in settings and defaults to calling the audit logger as presented here. Alternatively the audit logger could be a contrib (not sure about that though, having default loggin capabilities is not a bad idea, that's something worth discussing). The setting could remain and be used to bypass the hook call completely.

Agreed about the hook idea, I felt uncomfortable as-is forcing output to logfiles in a format of my own dictation. Switching this to use hooks would not only allow devs to determine what they want to capture, but also how they want to store it (this would be a good entrypoint to an ELK pipeline).

> This is unfortunately not a valid way to identify "unsafe" command names. You have hard-coded default command names here, whereas there is no telling these will be used by a given user. In fact, nothing in the core can depend on a specific command name.
One way around this would to have the blacklist of "unsafe" command names in settings, so that users can edit that as needed. It would be easy to cause an problematic security leak here though - it would be an easy-to-forget, obscure setting that would be easy to forget to update. A second and probably better option would be to introduce a special class variable no_log to commands like @password that you don't want to ever log.

This is an unfortunately sticky issue. The blacklist idea is likely the most practical, even with the potential of security leaks. Given the position at which I've chosen to MITM, I'm dealing with raw strings, not command objects, so I don't see how I'd be privy to class-level variables (and even then, whoever is writing a new sensitive-data-handling command would still have to be aware of the no_log variable and set it accordingly--- the leak still exists, now it's just somewhere else).

> The RawCmd( ... ) takes up a lot of space in the log. Would it not be better to clearly mark when user is not set and this might indeed be a spoof?

Yep. That was a quick and dirty solution on my part.

> I can see the motivation for not logging short 1-2 character inputs, but this can also lead to easy circumvention of the logging. For example users could use the @nick command to create a 1-2 character shortcut for a whole sequence of commands. The nick assignment would then be visible in the log but the actual invocation would not, making it hard to track events. I think it would be better to use some sort of blacklist for this as well, or a no_log variable as suggested above.

Ouch. I wasn't aware of `@nick`. Thanks for pointing that out!

@DamnedScholar 
> Sorry to take some of the thunder from this PR, but what if this were implemented differently? The same goal could be achieved by having each command call a global hook function and pass its own object to that function. If the command's __dict__ includes "audit": "false", for example, then the command would be excluded from the log. The implementation of a global "on command invocation" hook function would allow for a wide variety of other features to be built on the same foundation, such as having some commands interrupt others 

It's all good.

I did originally explore doing auditing at the command object level. Whether this is the right way to do it depends on what you want to get out of the resultant logs-- I decided against it because I want greater visibility into all strings users are throwing against the server, not just the ones that were successfully interpreted as commands. I'd like to know if users are trying to inject code or enumerate privileged commands that may or may not exist, for example, which is something that (if unsuccessful) would likely get filtered out as garbage before it ever reaches the command level.

But it could totally be done either way. Auditing at the command level would certainly be cleaner and allow much more selective flexibility.

@BlauFeuer 
> I think auditing is a good idea, but it's not something everyone wants implemented in the database or needs implemented in the server. The type of security needed will drastically vary with scope and deployment of the game, so much so that for the last ten years, nobody's addressed this need specifically.

Fair enough. One thing I'm seeing in this thread are two different use cases for logging (you all seem to be interested in different subsets of the data than me).

Auditing isn't sexy. This is a game development platform for making fun; auditing is actual work. Nobody wants to deal with it until a crisis happens, which leads to all sorts of desperate hacks to implement it post-incident. My goal here is to provide one easy-to-set-up, comprehensive option ahead of time.

@Griatch 
> strikaco's centralized logger offers the potential ability able to catch all outgoing data though (OOB, script echoes etc), for those that would want that.

Actually, it doesn't. I only capture inbound data. I did implement capture of outbound data too but it didn't work as I'd hoped-- a message broadcasted to all of a room's recipients creates one log entry per recipient. It's technically correct (each inhabitant did receive a copy of the same message) but I felt it would create too much of a logistical mess to be usable with the core toolset.

---

Thanks for all the feedback!

At this point I think the way to go might be adding a hook to the session handler and adding a hook to the base command object (`at_pre_cmd`) in core. This at least creates taps for whoever wants data from either source and doesn't force my particular implementation on everyone whether or not it's used.

Everything that follows as far as what to do with the data, or how to store it, could/should go in a contrib.

**Comment by BlauFeuer** [comment]
It has gone without saying, and I want to be sure it's clear to everyone, that we have **tekmunkey** (Not going to `@` this time) to thank for bringing the topic to the forefront.

My intent in all my discourse was to shape how this evolved, not to suppress or steal and reclaim ideas.  While part of what he wanted to do is possible now with https://github.com/evennia/evennia/wiki/Coding-FAQ#store-last-used-session-ip-address , other parts are not, and depending on your need or use case, **as strikaco** says so well, the right taps for hooks in the framework allows flexibility, and "doesn't force [any] particular implementation."

**Comment by DamnedScholar** [comment]
> I want greater visibility into all strings users are throwing against the server, not just the ones that were successfully interpreted as commands. I'd like to know if users are trying to inject code or enumerate privileged commands that may or may not exist, for example, which is something that (if unsuccessful) would likely get filtered out as garbage before it ever reaches the command level.

This sounds like a universal spying system. I feel like a lot of people would take issue with that.

**Comment by BlauFeuer** [comment]
@DamnedScholar I took issue with it on a particular MUSH where every command anyone enters is broadcast on a channel that some or all could subscribe to.  There's nothing stopping anyone from implementing it in their own game for Evennia.   Hooks for this exist now.  But there is a real legitimate need for being able to implement further security needs and debugging hooks.

**Comment by DamnedScholar** [comment]
There's absolutely nothing stopping anyone with shell access from monitoring everything that goes on in the game. But player trust will decrease if they know that there's omnibus auditing that's being monitored, without some statement about its usage and intent (the source code being public also helps).

**Comment by BlauFeuer** [comment]
Out of the box, no - I had to add my own code to see when someone was typing a command that went through NOMATCH, so when I looked at console (viewed from the shell), I could then in-game respond to the complaint of a thing not working with "You have to spell the command correctly, like so...."

Every game should have a privacy notice and something that mentions how long logs are kept and what's being logged, and the users decide (like I did with that particular MUSH) if they want to continue using such a system.  That's why I believe framework hooks should be in place to allow games to be user-extensible, but auditing shouldn't really be the core focus of the game or Evennia's framework, itself.

Believe me, if I thought this PR or that feature request was over-reaching, I would say something very much, until and after people were tired of hearing it.

**Comment by strikaco** [comment]
@DamnedScholar 

With regards to at_pre_cmd, I now remember my chief grievances against it-- too easy for a dev to override the hook and not call the parent, which would completely avoid the auditing hook, and the fact that command-spamming protection can also prevent the string from reaching this point. 

Beyond that I think it would still capture the raw command string, and you'd be working with proper objects instead of strings so it is definitely a more elegant solution.

> This sounds like a universal spying system. I feel like a lot of people would take issue with that.

I agree, but as any sort of server administrator you do have the right to log user activity. Just because a service doesn't say they aren't watching your every move doesn't mean they aren't actually doing it. Every GET request you make is logged by the host without disclosure. Hell, even services that market themselves as being anonymous and untraceable still monitor you and sell your information to China. It's an unfortunate reality of the world we live in today.

But just because you're logging everything doesn't mean you're compelled to spy on individuals. Just be ethical about it. Disclose up front that activity may be monitored, don't snoop and don't sell the data.

The shell access bit was addressed in the tekmunkey thread, and his counterpoint was valid-- that means you'd have to give moderators/GMs/whatever shell access. The goal is to provide an abstraction from the shell that moderators can access, ideally in-game.

**Comment by BlauFeuer** [comment]
Considering I don't need that level of auditing, I would be glad to be able to overwrite the auditing hook.  And if I can't overwrite it, I hope I can configure it to turn off in some setting somewhere.

When command spamming limiter is engaged, that's another thing that should be logged in #1383.  Silently thwarting attack attempts by brute login or command saturation is something that should appear in a log, and especially in auditing, should one feel the need for auditing.

**Comment by DamnedScholar** [comment]
My position is just that there are a lot of people in this community who have seen abuses in the past. Most of them know that it's ultimately a matter of trust, and they're willing to trust the server runner, but the server runner has to *seem* transparent. If nobody knows about a logging system, that's fine. If people know about a logging system and there's an explicit norm around its usage, that's usually fine. If it comes out that there's a logging system but the circumstances around it are secretive, that's when people stop trusting you.

I don't think that anybody in this discussion has indicated that they're intending to do anything bad or be less than transparent with their players, but I feel like the *subject matter itself* requires a bit of pre-emptive establishing of ethics.

**Comment by Kelketek** [comment]
@DamnedScholar There's not a way to establish ethics for the use of code you do not control. Once someone installs Evennia, we're no longer in control of it. We, at best, can provide a tool. It is up to those who use it how they use it. No amount of coding will either prevent or require anyone who uses this codebase to be a spy. The only thing in particular I would suggest is having sane defaults.

It's reasonable, in my opinion, to have some debug mode logger that can be enabled or disabled as needed. If you've got a bunch of friends beta testing, that'd be more what I'd use this sort of thing for. But anything which can be used to debug can be used to spy.

**Comment by CloudKeeper1** [comment]
Not entirely relevant, but the method I log inputs (and in fact asked for a specific change in Evennia to use this method) is through the [data_in and data_out methods](https://github.com/evennia/evennia/blob/master/evennia/server/serversession.py#L367) in the [serversession](https://github.com/evennia/evennia/blob/master/evennia/server/serversession.py). I use my own serversession and used [the log utility](https://github.com/evennia/evennia/blob/master/evennia/utils/logger.py#L242). Each player has a log file and it even captures the input and output prior to logging in. I essentially can see a players whole play through this way.

**Comment by Griatch** [comment]
@strikaco Bump. As said, I believe this belongs in a contrib and would be happy to see this PR converted to that.

**Comment by strikaco** [comment]
It's been a while since I've visited this. Since then I've made some modifications and run a modified core ServerSession that passes dicts containing the raw string and metadata for all strings inbound and/or outbound to a custom method specified in settings. Object references to the account, character, room and session are appended for the sake of those who wish to manipulate any of them directly.

Then I have a game-specific function that receives those dicts, drops the keys I don't need, masks sensitive commands, serializes the rest as json and logs it to disk. This is the simplest and most ideal solution in my opinion-- when enabled, core provides a firehose of data for the admin/analyst; how much of it is consumed and how it gets stored is game-specific. Compared to my previous PR this no longer dictates implementation of format, storage or content so this should be much more in line with project principles.

Here's a truncated gist of the modifications I made; it's the addition of an audit() function to ServerSession that gathers metadata and some checks at init, data_in and data_out to see if we need to be logging either direction. If it's acceptable I'll submit a proper pull request.

https://gist.github.com/strikaco/c12e860f74d918275712918e3bf203f0

**Comment by Griatch** [comment]
@strikaco Since the `ServerSession` is pluggable with `settings.SERVER_SESSION_CLASS`, your variant would work fine as a contrib I think!

**Comment by Griatch** [comment]
Closing, this is instead handled in the contrib proposed with #1535.

**Pull request closed without merging**
