### PR TITLE
Manager.py is returning a couple of querysets instead of lists. Fix for bug #2088

### PR DESCRIPTION
**Pull request by davidamandoestrada**
## Brief overview of PR changes/additions
Manager.py is returning a couple of querysets instead of lists. Fix for bug #2088

#### Motivation for adding to Evennia
https://github.com/evennia/evennia/issues/2088

### CODE REVIEW

**Comment by davidamandoestrada** [comment]
Oh sorry. I thought the doc strings said these methods returned lists. It also seems get_objs_with_key_or_alias can return empty lists. I'll update accordingly.

**Comment by Griatch** [comment]
@davidamandoestrada Yeah, it's an easy mistake to make, because there was a time were we *did* enforce a list-return from most of those managers. Homogenizing the api to give only one consistent return is an ongoing project. If doc strings still say they return list those need to be updated.

**Comment by Griatch** [comment]
@davidamandoestrada Is the plan to continue work on fixing issue #2088 here, or should this PR be closed?

**Comment by davidamandoestrada** [comment]
Yes, I'll work on it today.

**Comment by davidamandoestrada** [comment]
@Griatch I think I can just change the results to a list in objects.objects.DefaultObject.search

**Comment by Griatch** [comment]
@davidamandoestrada Yes, I think making sure that the DefaultObject.search converts the `result` to a list in all cases would make it the most consistent.

**Pull request merged**
