### PR TITLE
Add space to the tutorial's CrumblingWall message

### PR DESCRIPTION
**Pull request by jerryaldrichiii**
#### Brief overview of PR changes/additions
Simple message formatting fix

#### Motivation for adding to Evennia
You folks have an awesome thing here and I want to help where I can :smile:

### CODE REVIEW

**Comment by jerryaldrichiii** [comment]
I see other PR's are going to the develop branch, will rebase and set that as the base.

**Comment by jerryaldrichiii** [comment]
I saw other PRs are going to the develop branch. I rebased and set that as the base. Let me know if that was incorrect.

**Comment by Griatch** [comment]
Thanks! This is a simple bug fix/typo fix, so this one *should* actually go to `master` branch though. Only PRs with new features (or fixes to stuff only in development) go to the `develop` branch. :)

**Comment by jerryaldrichiii** [comment]
Sounds good, I fixed it. :smile:

**Pull request merged**
