### PR TITLE
Group search multimatches by displayed name

### LINKED ISSUE #3570: [BUG] Multimatching message adds unneeded numbers to non-identical partial-match results
#### Describe the bug
When a search matches multiple objects as partial matches, rather than exact matches, the multimatch messaging system adds a disambiguator index to each item based on its position in the entire list of results. This results in it giving disambiguated searches that won't actually return anything.

#### To Reproduce
1. Create one object named "red box" and two objects named "red block"
2. `py self.search("red")` will return the following:
```
More than one match for 'red' (please narrow target):
 red box-1
 red block-2
 red block-3
 ```
3. `py self.search("red block-3")` will fail to find anything, because there is no third "red block" object

#### Expected behavior
Ideally, the output for partial-match multimatches would look like this:
```
More than one match for 'red' (please narrow target):
 red box
 red block-1
 red block-2
```

#### Environment, Evennia version, OS etc
Evennia main aeb0cf6854
Debian linux

### PR DESCRIPTION
**Pull request by InspectorCaracal**
#### Brief overview of PR changes/additions
Modifies the multimatch output to iterate disambiguators only for results with matching names.

It's significantly more complex to make it remove the disambiguator entirely if only one match has a given display name, like the example in the related issue mentioned below, so the output instead looks like this:

```
>>> self.search('red')
More than one match for 'red' (please narrow target):
 red box-1
 red block-1
 red block-2
>>> self.search('red box-1')
red box
```

#### Motivation for adding to Evennia
Bug fixing

#### Other info (issues closed, discussion etc)
Resolves #3570

### CODE REVIEW

**Review by Griatch — APPROVED** [review]
Hm, this is an interesting one. Looks like a good fix, but it would be good to also add some unit tests here to actually showcase this behavior and make sure these grouped results actually work to disambiguate the results correctly.

**Review by Griatch — CHANGES_REQUESTED** [review]
Hm, this is an interesting one. Looks like a good fix, but it would be good to also add some unit tests here to actually showcase this behavior and make sure these grouped results actually work to disambiguate the results correctly.

**Comment by InspectorCaracal** [comment]
Good call, I'll add that!

**Review by Griatch — APPROVED** [review]
I wonder if depending on the `get_display_name` return to group things can have confusing side effects for games with heavily modified or dynamic `get_display_name` methods. :thinking: But the current behavior is already confusing, so this is still an improvement, thanks!

**Pull request merged**
