### PR TITLE
Plugin-ify the webclient

### PR DESCRIPTION
**Pull request by friarzen**
#### Brief overview of PR changes/additions

This is a pretty extensive re-organization of the Webclient to allow easier functional updates and extensions by compartmentalizing existing functionality into 'plugins,' self-contained units of code that can be added with a single <script> line in the base.html.

#### Motivation for adding to Evennia

The current implementation makes it hard to swap out components like the split.js interface or provide new functionality such as my hotbuttons branch. This provides a more flexible base.

#### Other info (issues closed, discussion etc)

Known issue: pulling out the splithandler exposes a CSS problem in the base gui where the scrollbars do not work and then eventually the input field scrolls off the bottom of the screen.

### CODE REVIEW

**Comment by Griatch** [comment]
@friarzen Didn't see this update in the IRC so pinging as a comment too.

**Comment by friarzen** [comment]
Hmm...that is the behavior when the splithandler plugin doesn't init().  Since the update I just did alters how the init() calls are made, it must be related.  I didn't see this in my testing, but maybe I did something dumb.

**Comment by Griatch** [comment]
@friarzen Looking in my browser console, I see this error: 

```
jquery-3.2.1.min.js:2:31569
jQuery.Deferred exception: ordered_plugins is not defined @http://localhost:4001/static/webclient/js/webclient_gui.js:275:19
j@https://code.jquery.com/jquery-3.2.1.min.js:2:29997
g/</k<@https://code.jquery.com/jquery-3.2.1.min.js:2:30313
 undefined 

webclient_gui.js:275:19
ReferenceError: ordered_plugins is not defined[Learn More] webclient_gui.js:275:19
<anonymous> http://localhost:4001/static/webclient/js/webclient_gui.js:275:19
j    https://code.jquery.com/jquery-3.2.1.min.js:2:29997
g/</k<   https://code.jquery.com/jquery-3.2.1.min.js:2:30313```

**Comment by Griatch** [comment]
Seems to work fine now! Merged!

**Pull request merged**
