### PR TITLE
Move to python3 style division.

### PR DESCRIPTION
**Pull request by ahmedcharles**
Note: / and // have the same behavior in python2.

### CODE REVIEW

**Comment by Griatch** [comment]
@ahmedcharles 

No they don't: 
```python
print 1 / 2.0
<<< 0.5
print 1 // 2.0
<<< 0.0 
```

Python does automatic type conversion if one of the divisors is a float. // turns off this functionality. What 3.0 changes is to change integer divisors to always return floats (contrary to Py2). 

So these changes may be ok, but if // is used explicitly it was to enforce a particular form of divisor behavior which you leave up to the divisor types if you use /.

**Comment by ahmedcharles** [comment]
Ah, this is more nuanced than I thought. I'll review them more carefully.

**Comment by Russell-Jones** [comment]
Have a look at [past.utils.old_div](http://python-future.org/compatible_idioms.html?highlight=old_div#division)

**Comment by ahmedcharles** [comment]
I think I actually got it correct this time. Mind talking a look?

**Comment by Griatch** [comment]
I don't know exactly how prettytable is supposed to work since that's a third-party lib we include, but it looks ok at a glance. Will do some more tests though.

**Comment by ahmedcharles** [comment]
I could remove the change from prettytable, though that wouldn't mean it would work correctly under python3 anyways. What about the other changes?

**Comment by Griatch** [comment]
I've ran this through a few tests and prettytable seems to display correctly as well, along with the websocket system used by the webclient. So merging it in. :)

**Pull request merged**
