### PR TITLE
Batchcode Build.py for the Tutorial World.

### PR DESCRIPTION
**Pull request by CloudKeeper**
Brief overview of PR changes/additions
This is a draft of a proposed Batchcode Build.py for the Tutorial World.

Motivation for adding to Evennia
Provide example Batchcode for a sizeable play space and direct comparison to the Tutorial World bulid.ev

Other info (issues closed, discussion etc)
Uploaded at this stage to get feedback on layout and other stylistic decisions.
Tested but would appreciate a second set of eyes.

### CODE REVIEW

**Comment by Griatch** [comment]
I think this looks good at a first inspection! Since this is a part of the tutorial however, It think it may be an idea to use the full functionality of the batchcode (while mimicing the functionality of the original `build.ev`), by using the batchcode functionality of splitting the build into sections with a `#HEADER` block and several  `#CODE` blocks (maybe one per room?). That way a user could step through the build and also re-run individual parts of it. It would then also serve as something to point to in the batchcode documentation ("look here for a longer example of batchcode"...).

**Comment by Griatch** [comment]
Ping to see if the bot echoes it this time ...

**Comment by CloudKeeper** [comment]
Roger that.

**Comment by Griatch** [comment]
@CloudKeeper Plan to wrap this one up so it can be merged?

**Comment by CloudKeeper** [comment]
How would you like the block separation done? We could have all the rooms created in the first block and then subsequent blocks will just be detailing the rooms individually? Or we could break it into a room each where it will make the rooms one at a time but only connect the exits if the destination room exists, but then each block will be artificially complicated with checks. What do you reckon?

**Comment by Griatch** [comment]
Hm, the batchcmd version already showcases the room-by-room stepping, so maybe it's not too bad an idea to build in one block and then gradually customize in others.

**Comment by Griatch** [comment]
@CloudKeeper Any progress on this?

**Comment by Griatch** [comment]
@CloudKeeper If this is to go into Evennia 0.9, this needs to be finalized very soon. If not, we should probably close this. Let me know.

**Comment by Griatch** [comment]
Since this has not seen any updates in a good while, I'm closing this PR. If you get around to try to finish it in the future, ping me here and I'll re-open.

**Pull request closed without merging**
