### PR TITLE
Thranduil's suggested fixes

### PR DESCRIPTION
**Pull request by BlauFeuer**
#### Brief overview of PR changes/additions
Thranduil's actionable suggestions, including a traceback fix due to typo, and use of "gust" when describing wind, instead of "gush"

#### Motivation for adding to Evennia
Prevent traceback on `@rename` usage, and use more specific adjective describing tutorial world weather.

### CODE REVIEW

**Comment by BlauFeuer** [comment]
Traceback (most recent call last):
  File "/home/griatch/evennia/evennia/evennia/commands/cmdhandler.py", line 496, in _run_command
    ret = yield cmd.func()
  File "/home/griatch/evennia/evennia/evennia/commands/default/building.py", line 1142, in func
    caller.mgs("You don't have right to edit this player %s." % obj)
AttributeError: 'Character' object has no attribute 'mgs'

**Comment by Griatch** [comment]
For reference, my use of "gush" was actually intentional - I intended a "gush" to be a "gust" filled with water on that rainy moor. ;) Heh - maybe you have to be Swedish to fully appreciate that one, so fair enough on removing it. :+1:

**Comment by Griatch** [comment]
Merged with a rebase.

**Comment by BlauFeuer** [comment]
I had seen the "gush" of wind many times and thought it to be poetic.  I'll always have the mental image of waves of water and wind even after it is removed.

**Comment by Griatch** [comment]
Hah, a little less poetry, a little more lingual correctness on that moor now. ;)

**Pull request closed without merging**
