### PR TITLE
#905

### PR DESCRIPTION
**Pull request by trhr**
Minimum viable patch for #2045 

Adds utils/commonstrings.py with a collection of extracted hardcoded strings

Began implementing utils/commonstrings.py across priority (user-focused) areas. To be continued.

### CODE REVIEW

**Comment by trhr** [comment]
Needs unit tests, not familiar with your testing methodology yet.

**Comment by Griatch** [comment]
@trhr Hm, it doesn't seem like #2045 is related to this. Are you referring to #905 maybe?

**Comment by trhr** [comment]
Griatch - two branches here.

The majority of the work is in the #905 branch, but earlier commits include #2045.

**Comment by trhr** [comment]
I have other changes for #2045 that I didn't submit as this PR, and it looks like I'll have to resubmit this PR because my dev environment didn't grab the commit that actually compiles. Before I do that, any thoughts to breaking out common strings to ease translation? Your #905 notes say you want to wrap individual strings with gettext, but there are a lot of places where strings are duplicated (and the translation would likewise have to be duplicated). This was an attempt to normalize some common structures, i.e. "Username/password is incorrect" is a fair way to respond to an auth problem on django login, on setpassword, on telnet auth, etc, and only needs to be translated once rather than three times, in this example.

**Comment by Griatch** [comment]
@trhr I have gone back and forth on whether to break out translatable strings into a separate module like this; 
- My main concern is that it makes it a harder to read the code - especially to grep the code for that error or feature you are looking for. Today you can just do `git grep "You have been banned and cannot ocntinue"` to find just where this text is coming from. 
- Admittedly it's just one step away to first find the string in `commonstrings.py` and then find the corresponding constant, but still. 
- So overall I think moving core strings into a common text lib does make things easier. So if you are willing to put in the work to do that, it should be a useful addition :) 

So on that note, I have a few points 

- A PR is one branch only. Aim towards one of the tickets per PR, please. 
- If you can, avoid doing code "prettification" just for the sake of it (like breaking up lists into multiple lines and the like). It tends to make the commit hard to review since one has to look around to find what is actually new functionality. Besides, we run `black` on the sources regularly, so your prettification changes will be lost anyway. 
- There are so many things in `evennia/utils/` already that I'm wondering if it's really the best place to put `commonstrings.py`. I wonder if `evennia/server` may not be a better location. I'm open to arguments though. 
- To reiterate and expand on the specification in #905, No command bodies are covered by i18n, and strings in Commands should _not_ be broken out into separate string constants. Not translating the Commands means that even with a fully fleshed out translation file, common game returns will be in the original language. This is deemed acceptable.  The reason for this is threefold: 
    1. Doing so makes command code more complex and harder to read 
    2. The default commands are intended to be easily replaceable. 
    3. Default game commands may still change and some refactorings of them are due. Spending time to translate them carries a risk of being a wasted effort. 
- There is no need to translate server-ops facing text (such as logging messages, launcher help etc). 
- What _needs_ translation are user-visible strings that are embedded to be returned in the core itself and which are generally not meant to be replaced by any other means. There could be some code here that are _used_ by Commands to output text; that would be ok to put under i18n.

**Comment by trhr** [comment]
Reworking this slowly, sort of mid-burnered for me; translation is a fairly high priority for my intended users, of which I have none yet until the rest of the system is built :)

**Pull request closed without merging**
