### PR TITLE
API Docs 1

### PR DESCRIPTION
**Pull request by tajmone**
My first ago at contributing to docstrings. I'm submitting a single file, lockfuncs.py
I've only worked on the first part of it, to see if it's ok. Feedback welcome!

### CODE REVIEW

**Comment by Griatch** [comment]
I'm merging it in, just know that you can keep adding commits to fix things like the tab - your additions will go along expanding the pull request. 
The docstring looks very good! The only thing to keep in mind is that sections (`# title`, `## subtitle` etc) should not be used in freeform docstrings, the `api2md` program will create those automatically. I clarified the coding style file a little to make this more clear. 

A good start! I fixed the tab and section and merged it.  You can see the result at https://github.com/evennia/evennia/wiki/evennia.locks.lockfuncs !

**Comment by tajmone** [comment]
I'm glad to ear that it was mostly ok.
I was in dobut about the sections headings, but since it was an appendix I tried it ...
I actually didn't manage to expand the request: I did change my local copy and removed the tab, but just didn't get around to pull in on top (somehow the option was disabled). 
I'm reading thoroughly the GitPro book, and experimenting with cli git, and I am also working with GitHub for Windows in the meantime, which makes some task a bit easier. The only difficoult thing with GH4W is that it uses a "metro" gui, and as most reviewers admit: it's difficoult to know where to click for an option. It seems there are no menus or options, then you click in a strange place and a whole pletora of options pops up. It's far beyond minimalistic! :(
I'll do my best to help with the docstrings, and have my chance to read through the source code and learn.
Tristano




----Messaggio originale----

Da: notifications@github.com

Data: 09/03/2015 8.21

A: "evennia/evennia"<evennia@noreply.github.com>

Cc: "Tristano Ajmone"<tajmone@gmail.com>

Ogg: Re: [evennia] API Docs 1 (#691)




I'm merging it in, just know that you can keep adding commits to fix things like the tab - your additions will go along expanding the pull request. 

The docstring looks very good! The only thing to keep in mind is that sections (# title, ## subtitle etc) should not be used in freeform docstrings, the api2md program will create those automatically. I clarified the coding style file a little to make this more clear. 


A good start! I fixed the tab and section and merged it.  You can see the result at https://github.com/evennia/evennia/wiki/evennia.locks.lockfuncs !

**Comment by Griatch** [comment]
I believe as long as you work in the branch you used for the pull request and push your local branch changes to the same branch to your upstream repository, Github (the website) will automatically include that in the pull request. 

I don't know about github4w but at least on the command line, it would look something like this:

```
# create new work branch and check it out
git br -b branchname
#
# (make changes)
#
# create new remote branch based on the current one
git push -u branchname
#
# (make Pull request on github)
#
# (Realize you need more changes
# and do them (in same branchname)
#
git commit -m "commit message" 
# push these changes to the remote branch
git push
```
So if you can replicate this flow in the gui somehow it *should* work unless your git version is very, very old. As long as you are on the same branch you originally pushed upstream (with `git push -u`), doing `git push` again should push to that upstream branch. Github (the website) will notice this automatically.

**Comment by tajmone** [comment]
You're right. All I need to do is commit and synch
When I synch all new changes are uploaded to GitHub and qued to previous ones in the same pull request.


Thanks


----Messaggio originale----

Da: notifications@github.com

Data: 09/03/2015 10.40

A: "evennia/evennia"<evennia@noreply.github.com>

Cc: "Tristano Ajmone"<tajmone@gmail.com>

Ogg: Re: [evennia] API Docs 1 (#691)




I believe as long as you work in the branch you used for the pull request and push your local branch changes to the same branch to your upstream repository, Github (the website) will automatically include that in the pull request. 


I don't know about github4w but at least on the command line, it would look something like this:

# create new work branch and check it out
git br -b branchname
#
# (make changes)
#
# create new remote branch based on the current one
git push -u branchname
#
# (make Pull request on github)
#
# (Realize you need more changes
# and do them (in same branchname)
#
git commit -m "commit message" 
# push these changes to the remote branch
git push



So if you can replicate this flow in the gui somehow it should work unless your git version is very, very old. As long as you are on the same branch you originally pushed upstream (with git push -u), doing git push again should push to that upstream branch. Github (the website) will notice this automatically.

**Pull request closed without merging**
