### PR TITLE
New CurrencyHandler module for contrib

### PR DESCRIPTION
**Pull request by KathyWithAK**
Currency Module for handling different forms of currency and converting between currencies within the CurrencyHandler. Originally based off the Traits Module from contrib.

### CODE REVIEW

**Comment by Griatch** [comment]
Interesting; but you seem to be pulling in the entire WIP `collab` PR along with this PR. This is likely because you made your PR off the collab branch rather than off the develop branch. Since collab is not ready to merge, please remake this to be off the normal develop branch instead so you add only the module you want to contribute.

**Comment by KathyWithAK** [comment]
First time I have ever tried to do a contrib. I will try again.

**Comment by Griatch** [comment]
@KathyWithAK Any progress on this?

**Comment by KathyWithAK** [comment]
I haven't taken a look at it since March. I may try to look at it this
week, but it will depend on what my work schedule looks like.



Kathy

**Comment by KathyWithAK** [comment]
I went ahead and reforked the evennia code from the develop branch and submitted a new pull request based on that. That should make this request defunct.

**Pull request closed without merging**
