### PR TITLE
Updated italian translations

### PR DESCRIPTION
**Pull request by MattiaEffendi**
#### Brief overview of PR changes/additions

I've updated the italian translation with the new strings.

#### Motivation for adding to Evennia

The translation was last updated in 2015, and so a strings refresh was needed as mentioned in #2884

#### Other info (issues closed, discussion etc)

See #2884, also if you want this PR could be considered as an Hacktoberfest contribution 😄

### CODE REVIEW

**Review by Griatch — APPROVED** [review]
@MattiaEffendi Thanks! This definitely counts towards Hacktoberfest :grinning:

**Comment by Griatch** [comment]
@MattiaEffendi ...but unfortunately this was done against the `master` branch. We do only translation updates against `develop` branch, as mentioned in that issue. I was too quick to merge this, and now reverted it. Please re-direct this PR towards the `develop` branch. You may need to rebuild the po file to see what changed.

**Comment by MattiaEffendi** [comment]
@Griatch no problem, i will re-open the PR towards develop ASAP!

**Comment by Griatch** [comment]
Thanks! :+1:

**Pull request merged**
