### PR TITLE
Enhanced geoip and contextual connection wrappers

### PR DESCRIPTION
**Pull request by strikaco**
#### Brief overview of PR changes/additions
This PR addresses two issues:

Evennia `Session` objects and Django `HttpRequest` objects both handle TCP connections yet have almost no properties in common. They both share the concept of useragents, source IP address, protocol and others but the names of these properties are not consistently accessible. So for operations like banning an IP address from the terminal and webserver, you have to implement two different procedures for handling what is ultimately a simple text string. This PR provides a wrapper for both classes that handles identification and extraction of appropriate properties, so to get the IP address from either, you can do `SessionWrapper(session).ip` or `RequestWrapper(request).ip` to get the same data.

The second component to this PR extends Django's own geoip contrib to retrieve AS data (or ISP data, for those with the appropriate licensing) as well as the specific CIDR block of a given IP. With this added context, one can more accurately identify where users are coming from and what infrastructure they are using when anonymously conducting harassment campaigns. No more assumptions of /24 subnets need to be made or blocking entire class Bs using wildcards; we can extend the ban mechanisms to block by any artifact-- admins can now be empowered to ban an entire country, a particular service provider, or a specific subnet, which are functions you normally have to have a standalone WAF or pay Cloudflare to do.

The two integrate in a manner such that if you wrap a `Session` or `Request`, you can easily drill into connection details without any special magic. `SessionWrapper(session).isp` will output something along the lines of `Verizon Wireless`.

#### Motivation for adding to Evennia
The capacity for trolls to cause damage generally outscales most applications' ability to stop them, Evennia being no exception. Being terminal-based it is susceptible to all of the same sorts of scripted problems that plague IRC. Being able to classify traffic would go a long way towards filtering out that which is bad.

### CODE REVIEW

**Comment by Griatch** [comment]
Note that I moved the `auditing` PR into this same `contrib/security/` package too.

**Comment by Griatch** [comment]
For mocking out the unavailable imports, see my comments to pull #1664 [here](https://github.com/evennia/evennia/pull/1664#commitcomment-30795923)

**Comment by Griatch** [comment]
@strikaco This appears to still have issues with the mocking?

**Comment by Griatch** [comment]
Any progress on this?

**Comment by strikaco** [comment]
I don't have time to continue work on this; closing.

**Comment by Griatch** [comment]
@strikaco Sorry to hear that :(

**Pull request closed without merging**
