### PR TITLE
Markup, LGTM, PEP 8 updates (To complete #1212)

### PR DESCRIPTION
**Pull request by BlauFeuer**
### Brief overview of PR changes/additions
Markup and PEP 8 updates to `commands/default/batchprocess.py`

Markup, PEP 8 and ~~convert Prettytable to EvTable usage in `@bans` helper function of `commands/default/admin.py` and various tables in `commands/default/player.py`~~

LGTM alert fixes and PEP 8 whitespace updates in `players/players.py`

### Motivation for adding to Evennia
Per #1212, #1176,  ~~[Remove prettytable from evennia/utils](https://github.com/evennia/evennia/projects/6) directive for 0.7 devel branch~~ and generally keeping to PEP 8 style

### Other info (issues closed, discussion etc)
The first two files were in my local repository, but did not get committed with the others before closing #1212.

~~**As a result of editing two of the files submitted for pull:
_No more import of prettytable was found, so there should be no more usage of prettytable in current code._**~~

### CODE REVIEW

**Comment by BlauFeuer** [comment]
@Griatch ... the test coverage decreased, perhaps from removing the prettytable import which may have been under test.  Sorry, now we're below 50% again.

**Comment by BlauFeuer** [comment]
@Griatch ... the test coverage decreased, perhaps from removing the prettytable import which may have been under test.  Sorry, now we're below 50% again.

**Comment by TehomCD** [comment]
One very slight potential issue with the removal of PrettyTable and converting to EvTable exclusively - while EvTable is definitely far superior for readability for almost all situations when the table size is small, it runs noticeably slower if you have a fairly large table. If a table has, say, a hundred rows, there's actually a perceptible delay for building it, while PrettyTable runs about 5 times as fast or so. I actually reverted to using PrettyTable in a few instances whenever the number of rows for a table was over 20 to avoid complaints of it feeling unresponsive. Keeping it as a contrib would certainly be fine for it as an edge case, I'd just caution against removing it entirely.

**Comment by Griatch** [comment]
@TehomCD Are these tables with color tags in them? Prettytable generally cannot handle ansi code markers as I recall. Do you have an example of code you use for building a (slow) EvTable?

**Comment by TehomCD** [comment]
Here's a sample that I quickly converted from PrettyTable to EvTable for testing:
```
    def list_actions(self):
        from server.utils.prettytable import PrettyTable
        if "old" in self.switches:
            qs = CrisisAction.objects.filter(sent=True)
        else:
            qs = CrisisAction.objects.filter(sent=False)
        if "needgm" in self.switches:
            qs = qs.filter(story__exact="")
        if "listquestions" in self.switches:
            qs = qs.filter(questions__isnull=False, questions__answers__isnull=True)
        if self.args:
            qs = qs.filter(Q(crisis__name__iexact=self.args) |
                           Q(dompc__player__username__iexact=self.args))
        # table = PrettyTable(["{w#{n", "{wCrisis{n", "{wPlayer{n", "{wAnswered{n", "{wQuestions{n", "{wDate Set{n"])
        # for ob in qs:
        #     date = "--" if not ob.crisis.end_date else ob.crisis.end_date.strftime("%x")
        #     questions = "{rYes{n" if ob.questions.filter(answers__isnull=True) else "{wNo{n"
        #     table.add_row([ob.id, ob.crisis.name, str(ob.dompc), "{wYes{n" if ob.story else "{rNo{n", questions, date])
        table = EvTable("{w#{n", "{wCrisis{n", "{wPlayer{n", "{wAnswered{n", "{wQuestions{n", "{wDate Set{n")
        for ob in qs:
            date = "--" if not ob.crisis.end_date else ob.crisis.end_date.strftime("%x")
            questions = "{rYes{n" if ob.questions.filter(answers__isnull=True) else "{wNo{n"
            table.add_row(ob.id, ob.crisis.name, str(ob.dompc), "{wYes{n" if ob.story else "{rNo{n", questions, date)
        self.msg(table)
```
For 80 rows, when it's PrettyTable, it executes in 350 ms or so. When it's EvTable, it's 2200ish ms or so. If the rows have cells that need to wrap, such as if I made date's `strftime("%x %M:%D")`, for example, it'd increase the time proportionally based on the number of additional rows it adds, it seems. Say to around 2800ms or so. Conversely, while it breaks PrettyTable's display and makes it look awful, there's no meaningful difference in performance for row size.

I do think this is probably an edge case because it only happens if you're dealing with very large tables, but it might possibly come up if people use `EvMore` to limit the display, since they'd still incur the cost of building the table that is passed to EvMore the first time they generate it. I only noticed it at all because one of the tables returned by a staff command was monstrous, something like 300 rows, and it was a noticeable delay - I was surprised to see that it was EvTable rather than the query that was the bottleneck.

**Comment by Griatch** [comment]
@TehomCD Ok, will check that. The main expense I expect to be the `add_row` operation in that case; EvTable will need to recalculate the row size and possibly adjust the table (EvTable allows adding non-symmetric rows/columns and expect the table to automatically fill in with empty slots, something prettytable doesn't do at all). I'm not sure if this happens for every new addition but I do recall this being the slower mode. I imagine creating the table in one go with EvTable(table=[[...], [...], [...]]) will be a lot faster for this use case.

**Comment by TehomCD** [comment]
I just tried a version with:
```
rows = []
        for ob in qs:
            date = "--" if not ob.crisis.end_date else ob.crisis.end_date.strftime("%x %M:%H")
            questions = "{rYes{n" if ob.questions.filter(answers__isnull=True) else "{wNo{n"
            #table.add_row(ob.id, ob.crisis.name, str(ob.dompc), "{wYes{n" if ob.story else "{rNo{n", questions, date)
            rows.append([ob.id, ob.crisis.name, str(ob.dompc), "{wYes{n" if ob.story else "{rNo{n", questions, date])
        table = EvTable("{w#{n", "{wCrisis{n", "{wPlayer{n", "{wAnswered{n", "{wQuestions{n", "{wDate Set{n",
                        table=rows)
        self.msg(table)
```
And still took around 2500ms. I couldn't get it to let me set width to 78 - if I tried, it returned an error saying:
```
File "c:\arx\evennia\evennia\utils\evtable.py", line 1527, in __str__
    return  str(unicode(ANSIString("\n").join([line for line in self._generate_lines()])))
  File "c:\arx\evennia\evennia\utils\evtable.py", line 1333, in _generate_lines
    self._balance()
  File "c:\arx\evennia\evennia\utils\evtable.py", line 1250, in _balance
    raise Exception("Cannot shrink table width to %s. Minimum size is %s." % (self.width, cwmin))
Exception: Cannot shrink table width to 78. Minimum size is 321.
```
Not sure if I was just doing something wrong there with the formatting of the table or if that's a bug.

**Comment by Griatch** [comment]
@TehomCD I'm pretty sure you must add columns, not rows, this way.

**Comment by TehomCD** [comment]
Ah, okay. I see now. I think I did it properly this time, with
```
        col1 = []
        col2 = []
        col3 = []
        col4 = []
        col5 = []
        col6 = []
        rows = [col1, col2, col3, col4, col5, col6]
        for ob in qs:
            date = "--" if not ob.crisis.end_date else ob.crisis.end_date.strftime("%x %M:%H")
            questions = "{rYes{n" if ob.questions.filter(answers__isnull=True) else "{wNo{n"
            #table.add_row(ob.id, ob.crisis.name, str(ob.dompc), "{wYes{n" if ob.story else "{rNo{n", questions, date)
            #rows.append([ob.id, ob.crisis.name, str(ob.dompc), "{wYes{n" if ob.story else "{rNo{n", questions, date])
            col1.append(ob.id)
            col2.append(ob.crisis.name)
            col3.append(str(ob.dompc))
            col4.append("{wYes{n" if ob.story else "{rNo{n")
            col5.append(questions)
            col6.append(date)
        table = EvTable(table=rows, width=78)
        self.msg(table)
```
and was still around 2700 ms.

**Comment by Griatch** [comment]
@TehomCD 
Ok, could you please write this up as a feature request for speeding up EvTable? I'm not sure we can do all the processing EvTable does any faster, but we migth add a "fixed" mode if you don't need all the dynamic load balancing and accepts that it will print stuff just the way you enter it.

**Comment by BlauFeuer** [comment]
Since the prettytable to EvTable has been shown not to be an optimization at this time, and the original PR was intended to release the final two files to satisfy #1212, I've moved the prettytable->EveTable edits in two module to another PR.

**Comment by Griatch** [comment]
@BlauFeuer I'd say, keep the prettytable removal in. The slowdown @TehomCD is talking about is not in the commands you converted to EvTable necessarily, but in his custom commands using much bigger tables.

**Comment by BlauFeuer** [comment]
@Griatch The `@bans` command in evennia/commands/default/admin.py could reach 100 or more entries, and the who list in evennia/commands/default/player.py regularly does on Arx.  I only tested with 1 or 2 entries on both and didn't visually notice a difference.

If the last two PR commits, ab12965 and f17e42b, are not pulled, then this PR includes the prettytable to EvTable conversion. Without the last two, Coveralls will report test coverage dropping below 50%.

I could submit another PR against devel, keeping the prettytable conversion for 0.7, or it could be rolled in with the feature request to add a less-flexible speed mode to EvTable, or I could commit an undoing of the undoing of the prettytable conversion in this PR...

I'm open to all options.

**Comment by Griatch** [comment]
Merged with a rebase. I chose to keep your removal of prettytable; we'll see if it has an impact or not.

**Pull request closed without merging**
