### PR TITLE
Makes webclient/terminal auto-puppet character selected on website

### PR DESCRIPTION
**Pull request by strikaco**
#### Brief overview of PR changes/additions
This PR makes it so that if you select a character on the website and then hop into the game, you'll automatically become that character.

Also adds a link to the puppet activation URL as an action on the character management page.

#### Motivation for adding to Evennia
Currently the character quick-select on the website is cosmetic only and does nothing out of the box.

### CODE REVIEW

**Comment by Griatch** [comment]
I'd think this depends highly on `MULTI_SESSION_MODE`. Did you test this with a mode > 1? I imagine it has no effect there (which is correct, but might maybe come off as confusing)

**Comment by strikaco** [comment]
Hmm true. On mode 2 it just takes you to the 'select a character' screen in the terminal.

**Comment by Griatch** [comment]
I wonder if one would need to handle this case somehow, maybe turn off this functionality depending on `MULTI_SESSION_MODE`?

**Comment by strikaco** [comment]
I'm not sure that's desirable though. The function of the dropdown system was supposed to be to allow devs to create mail forms, comments, bulletin boards, whatever on the site and let players interact with web resources in the context of a character-- specifically designed *for* the higher multisession modes. 

This particular PR just gives the dropdown more of a function instead of the appearance of doing nothing. "You become ___"-- great, now what?

**Comment by Griatch** [comment]
@strikaco I think the solution to this is to make it very clear that this is just a stub functionality. If nothing happens when you select it, people will mark it as a bug. It would be clearer if instead it lead to the Not-implemented page (or, I don't know, maybe a popup?) saying something to the effect of 
```
This functionality is not implemented by default - it's up to you 
to add the functionality you want for your own game!
You can find a useful turorial for how to do this [here].
```

**Comment by Griatch** [comment]
@strikaco This appears to only need the stub functionality for other multisession-modes. Or do you have another suggestion?

**Comment by strikaco** [comment]
I did not see your Dec 2 suggestion; I think that should be fine. Will try to implement when I get a chance.

**Comment by Griatch** [comment]
@strikaco If this is to go into Evennia 0.9, this needs to be finalized very soon. Please let me know what the status is.

**Comment by Griatch** [comment]
@strikaco Any plans of wrapping this up or should this PR close?

**Comment by strikaco** [comment]
Yeah I'll go ahead and close this; I no longer remember where I was going with it.

**Pull request closed without merging**
