### PR TITLE
#1445 #1709 - Latinify character names in .create()

### PR DESCRIPTION
**Pull request by trhr**
#### Brief overview of PR changes/additions
Forces character names to be Latin script, preventing unicode injection

#### Motivation for adding to Evennia
1.0 gogogo

### CODE REVIEW

**Comment by strikaco** [comment]
This is very useful but something of a misnomer. Your `_validate` function is actually *normalizing* the input string, not asserting whether it is valid.

It is a potential source of confusion and ambiguity because implementation on `Account` objects does distinguish between the two.

https://github.com/evennia/evennia/blob/10a6685fdf56c25c3e175df6753506af12f40d11/evennia/accounts/accounts.py#L544-L601

**Comment by trhr** [comment]
Yeah, I agree. It's normalizing.

I was going to hook it into some kind of setting that would allow people to write "no numbers in usernames" but I didn't because the more I looked at it the more I hated giving any kind of default.

**Comment by strikaco** [comment]
Heh, that's the reason I haven't touched #1709 in years :)

The best I've come up with is defining a mixin with a class-level regex and extending `create()` to check it before running the parent hook.

```
import re

class KeyValidator(object):

    key_regex = '^([a-zA-Z][a-zA-Z0-9\-\_\s]{2,30})$'

    @classmethod
    def validate_key(cls, key, *args, **kwargs):
        bool = kwargs.get('bool', False)
        if not re.match(cls.key_regex, key):
            if not bool: raise UserException(f"Name '{key[:6]}...' contains invalid characters.")
            return False
        return True

    @classmethod
    def create(cls, *args, **kwargs):
        key = kwargs.get('key', args[0])

        # Check for valid key
        cls.validate_key(key, **kwargs)

        return super().create(*args, **kwargs)
```

**Comment by trhr** [comment]
I like the idea of making this standard functionality, but I also like the fact that right now, it solves the security issues and won't have a big impact on the playerbase. If there's some Swedish dev out there who writes their character names in squiggles, they can just overload and return txt to make this functionality not exist.

**Comment by trhr** [comment]
@Griatch - the Accounts already have both normalize and validate, but because they have to work with Django, they use Django hooks.

```
    def normalize_username(cls, username):
        """
        Django: Applies NFKC Unicode normalization to usernames so that visually
        identical characters with different Unicode code points are considered
        identical.

        (This deals with the Turkish "i" problem and similar
        annoyances. Only relevant if you go out of your way to allow Unicode
        usernames though-- Evennia accepts ASCII by default.)

        In this case we're simply piggybacking on this feature to apply
        additional normalization per Evennia's standards.
        """
        username = super(DefaultAccount, cls).normalize_username(username)

        # strip excessive spaces in accountname
        username = re.sub(r"\s+", " ", username).strip()

        return username
```

I don't really want to apply custom validators/normalizers to accounts, since that's a Django thing and it could cause maintenance issues down the road. I suspect the code won't break if a character name is slightly-more-normalized than an account name, but I'll also update tests to include invalid names, if it's not already doing it.

**Pull request closed without merging**
