### PR TITLE
Auditing

### PR DESCRIPTION
**Pull request by strikaco**
## Brief overview of PR changes/additions

Adds a modified ServerSession that passes dicts containing the raw string and metadata for all strings inbound and/or outbound to a user-defined method specified in settings. Object references to the account, character, room and session are appended for the sake of those who wish to manipulate any of them directly.

Adds previously requested docstrings and scrubs default commands for password leakage.

## Motivation for adding to Evennia

More enhanced logging/auditing is a common requirement for server administrators, though how it should be implemented has been a controversial issue. This implementation is designed to avoid dictation of format, storage method or content and be more in line with project principles.

## Other info (issues closed, discussion etc)

Supercedes #1390 and #1535 and #1651. I untangled all my branches (I'm starting to git a clue) so hopefully this is the end of my PR spam campaign.

### CODE REVIEW

**Comment by strikaco** [comment]
Hey thanks; I haven't followed up with you yet since there are some other minor things I'd like to fix before anybody puts it in production so I'll write up a readme when I get back to this.

(Note to self: CmdNewPassword emits the password in cleartext msg to caller and target, need to write regex + test for)

**Comment by Griatch** [comment]
@strikaco If you have the time, please wrap this up for inclusion with Evennia 0.8.

**Comment by strikaco** [comment]
@Griatch Ready for review...!

**Comment by Griatch** [comment]
@strikaco Merged, thanks! I made the following changes as part of the merge: 

- Moved the contrib into a new subdir `contrib/security/auditing/` and updated all links, tests and READMEs to reflect this
- Changed README to indicate the default value for each settings variable
- Set the default callback to the one supplied, to allow using the contrib with minimal lines of settings
- Some minor style cleanups. 

I think it makes sense to group other security-related modules under the same package in the future.

**Pull request merged**
