### PR TITLE
Add post-creation and spawn hooks to DefaultObject

### PR DESCRIPTION
**Pull request by InspectorCaracal**
#### Brief overview of PR changes/additions
This adds two additional hooks to `DefaultObject` and integrates them into the appropriate locations.

1. `at_object_post_creation` - An additional hook which is added to `at_first_save` *after* the attributes etc. from `create_object` or prototypes have been applied. Named to match the pattern of `at_object_post_copy`
2. `at_object_spawn` - A specific hook intended for additional post-spawning processing of updates applied by a prototype. It is called both when the object is initially spawned, and when the object is updated to match any changes to the prototype.

#### Other info (issues closed, discussion etc)
This should fulfill the feature requests and use-case requirements presented in #3095

#### Additional notes
I played it safe when integrating the new `at_object_spawn` hook into the spawner code and used `getattr`, just in case someone decides to use the prototype spawner in unexpected ways like spawning accounts or something.

### CODE REVIEW

**Review by Griatch — CHANGES_REQUESTED** [review]
This is great, thanks for adding this, with the recent discussion in chat, this will be useful! 

- I think the hook should rather be `at_object_post_spawn` to be consistent; this is something that is explicitly happening the last thing in the spawn sequence
- I think it would be useful to have the hook include the prototype as an optional argument (`prototype=prototype`), or even better as `**prototype`. There could be some situations where having info about the prototype could be useful and not all prototype keys (like meta prototype keys) are reflected on the created object.  

> Going beyond the scope of this PR, I was thinking about if it would be useful to have a separate `at_object_spawn(**prototype)` method happening before creation where very industrious people could massage the prototype (maybe apply their own custom FuncParser?) just before it goes into spawning. But not sure if this is overkill, I've not heard anyone actually needing this. :sweat_smile:

**Comment by InspectorCaracal** [comment]
> happening before creation where very industrious people could massage the prototype

Oh, good point! I actually do both custom pre- and post-processing on my prototype-spawned objects, so I can think of use-cases.

My main thought on those suggestions is that I feel that if there's both an `at_object_spawn` and an `at_object_post_spawn`, and one of them is passed a dictionary of the prototype, they should both be receiving it the same way to be consistent. That makes me think it would be better to do `prototype=prototype` rather than `**prototype`

**Comment by Griatch** [comment]
@InspectorCaracal Ping :) Is there any more feedback you need for me?

**Comment by InspectorCaracal** [comment]
Sorry this took so long. :sweat: I decided to opt for the prototype keyword to avoid potential future-update or subclassing conflicts between prototype keys and custom keyword arguments.

**Comment by Griatch** [comment]
@InspectorCaracal Is this ready for re-review (I see you've made changes but you haven't pressed the little spinner up by my name, so I'm not sure)? :sweat_smile: )

**Comment by InspectorCaracal** [comment]
I could have sworn I did, whoops.

**Review by Griatch — APPROVED** [review]
Looks good. Reminder to self to update the documentation with these hooks.

**Pull request merged**
