### PR TITLE
Docstrings 4

### PR DESCRIPTION
**Pull request by tajmone**
More docstringing: 8 files...

### CODE REVIEW

**Comment by Griatch** [comment]
Again, please pull latest master and work off that for new pull requests. This is the same conflicts I've now resolved three times. :)

**Comment by Griatch** [comment]
The strings looks good! Merged with rebase.

**Comment by Griatch** [comment]
By the way, what I mean by switching to a "fresh branch after a merge" is to go to whichever branch you keep a "fresh" Evennia version and do `git pull` to get the latest version (this will include your work that I have merged into main in a clean way). I think you might be missing this step. 

That way the revision history will be in sync with the official one. Off this you can now make a new branch and modify away. We will then be in sync up to the point of new revisions you make. That new branch you then push online and make a merge request for.

**Comment by tajmone** [comment]
But this is what i did, and I don't understand why with Docstrings 4 you got also old pull requests.
What happened before this step is that I had some merge conflicts when pulling the latest version--but the conflict wasn't a real issue, because the new remote master already contained the changes, so.... But I solved them and only after "downloading" the latest version I created docstring number "4". 
I'm sorry, I just don't understand what went wrong. Somewhere in my head everything seemd right :(
It's that GitHub for Windows! It's no good, really. It lacks any kind of feedback, its too "minimalist", I never know exactly whats happening behind the scenes.
But this last operation I actually carried it out from shell ... Boh! Mistery!
By the way, I've manage to install Evennia on my RaspberryPi, and it works. I only need to setup the iptables before connecting it.
Tristano




----Messaggio originale----

Da: notifications@github.com

Data: 09/03/2015 18.54

A: "evennia/evennia"<evennia@noreply.github.com>

Cc: "Tristano Ajmone"<tajmone@gmail.com>

Ogg: Re: [evennia] Docstrings 4 (#696)




By the way, what I mean by switching to a "fresh branch after a merge" is to go to whichever branch you keep a "fresh" Evennia version and do git pull to get the latest version (this will include your work that I have merged into main in a clean way). I think you might be missing this step. 


That way the revision history will be in sync with the official one. Off this you can now make a new branch and modify away. We will then be in sync up to the point of new revisions you make. That new branch you then push online and make a merge request for.

**Pull request closed without merging**
