### PR TITLE
(WIP) Collab

### PR DESCRIPTION
**Pull request by Kelketek**
Opening this pull request as WIP to get feedback and more eyes on it. It is not ready for proper merge, but a few commits might be worth cherry-picking early, such as the Typeclass-aware QuerySets, and the ability to check different lock types from one lock string. Just let me know if you're going to do that so I can handle any rebasing/commit fiddling accordingly on my end.

### CODE REVIEW

**Comment by ahmedcharles** [comment]
Wouldn't it be better to have this PR against devel instead of master?

**Comment by Kelketek** [comment]
@ahmedcharles This PR predates the devel branch.

**Comment by Kelketek** [comment]
@Griatch This has been rebased. If you could look over it again at your next opportunity, that would be great. I think I addressed most of the notes you had previously, but it's been a good long time since then.

**Comment by Kelketek** [comment]
Closing in favor of another PR which shall be internal instead of across forks for better visibility.

**Pull request closed without merging**
