### PR TITLE
Addition of BROADCAST_SERVER_RESTART_MESSAGES flag to notify all sessions that the server is restarting.

### LINKED ISSUE #2506: [Feature Request] Make reload/reset/shutdown messages toggleable via settings.py
#### Feature:
I'd like the ability to turn off `... Server restarted.` from displaying to users for the sake of immersion. Ideally could do this with a boolean in `settings.py`.

### PR DESCRIPTION
**Pull request by Henddher**
Addition of BROADCAST_SERVER_RESTART_MESSAGES flag to notify all sessions that the server is restarting.

Resolves #2506

### CODE REVIEW

**Comment by Henddher** [comment]
Hi @Griatch, is there any trick to build+test changes against the `develop` branch?

As you see, these changes aren't passing the CD/CI checks.
Suggestions?

**Comment by Griatch** [comment]
@Henddher Thanks for the PR(s)! The build for develop was failing not because of anything you did but because it was testing a performance-timing and the CI build environment is pretty slow. I disabled that check now so it should pass again.

**Comment by Griatch** [comment]
Oh, and the `scipy` requirement belongs in the optional `requirements_extra.txt`. I moved it there now before merging (it was indeed missing).

**Comment by Henddher** [comment]
Thanks @Griatch !!

**Pull request merged**
