### PR TITLE
Docstrings 3

### PR DESCRIPTION
**Pull request by tajmone**
More docstrings ... 

And my first attempt to doc a function mysefl (please: double-check!)

### CODE REVIEW

**Comment by Griatch** [comment]
Note: Once I have merged your previous pull request, it's best if you base your new changes on a new branch off the latest master. This is because I rebase the changes into master and will run into merge conflicts if you re-open merge requests on the same branch over and over.

**Comment by Griatch** [comment]
Merged with rebase.

**Comment by Griatch** [comment]
Oh, and as far as I can tell the function docs looks good the way you did it!

**Comment by tajmone** [comment]
Yes, I've just noticed. I didn't realize how fast you'd respond, and on the other hand I haven't worked out which would be an optimal time to pull requests (ie: if I wait too long it might be that the file I work on is handled elsewere, and so on).
I think I'll dwelve again into the Pro Git book now... With practice new questions arise!
I'm doing my best, and I am coming to grips with the whole system. Hopefully, a couple of more days and I should be aligned into the workflow and cause less issues.
I am also getting a bit more confident with this googlestyled doc strings ... I realize that it's not super-strict and has more to do with readability (in-code and in-Wiki) than anything else. So I am keeping it to the minimum essential. I stop whenever the slightest doub arises (after all, its not my code, so I don't like licenses) but also take initiative whenever the required spirit of intervention is clear enough.
Luckily the cold weather is almost gone, and with it the worst of my hands-related problems (in winter its painful, in summer much less, temperature and moisture influence much its state).
Thanks!
Tristano




Note: Once I have merged your previous pull request, it's best if you base your new changes on a new branch off the latest master. This is because I rebase the changes into master and will run into merge conflicts if you re-open merge requests on the same branch over and over.

**Comment by Griatch** [comment]
@tajmone 

No problem, I just happened to be looking at it and be able to pull the request when I got it, it's usually not quite this quick. :) Just making you aware of it.

And yes, the google style markdown is really not all that strict, and my parser isn't either. I think the stuff you have made so far looks very good. 

For more reference, I made the `evennia/objects/objects.py` model pretty much complete as a second example of various doc strings in different forms.

**Pull request closed without merging**
